"""Add social and community schemas

Revision ID: fcdf956aa2f0
Revises: 10a48ddf9518
Create Date: 2026-07-21 20:47:23.106725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import geoalchemy2
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'fcdf956aa2f0'
down_revision: Union[str, None] = '10a48ddf9518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    op.create_foreign_key(None, 'mood_context_tags', 'mood_entries', ['mood_entry_id'], ['id'])
    op.create_foreign_key(None, 'mood_emotions', 'mood_entries', ['mood_entry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mood_emotions', type_='foreignkey')
    op.drop_constraint(None, 'mood_context_tags', type_='foreignkey')
    pass
